// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZSU64U7e6ro0mOGc7OhFli0DWvAFxT8',
    appId: '1:227408311679:web:51f75c1d52f9c7d166964a',
    messagingSenderId: '227408311679',
    projectId: 'quiz-89939',
    authDomain: 'quiz-89939.firebaseapp.com',
    storageBucket: 'quiz-89939.firebasestorage.app',
    measurementId: 'G-7XMGDDL8DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nUVwaRJvkJPhF_zU--FSLzcPE0UwYuc',
    appId: '1:227408311679:android:58f64c45fcc027d366964a',
    messagingSenderId: '227408311679',
    projectId: 'quiz-89939',
    storageBucket: 'quiz-89939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqlC4TJ29QHTNQ3GmTNvi5K7xcxwy30w',
    appId: '1:227408311679:ios:80ada762eed4438366964a',
    messagingSenderId: '227408311679',
    projectId: 'quiz-89939',
    storageBucket: 'quiz-89939.firebasestorage.app',
    iosBundleId: 'com.example.quizApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRqlC4TJ29QHTNQ3GmTNvi5K7xcxwy30w',
    appId: '1:227408311679:ios:80ada762eed4438366964a',
    messagingSenderId: '227408311679',
    projectId: 'quiz-89939',
    storageBucket: 'quiz-89939.firebasestorage.app',
    iosBundleId: 'com.example.quizApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvZSU64U7e6ro0mOGc7OhFli0DWvAFxT8',
    appId: '1:227408311679:web:7c7d45a8322a450166964a',
    messagingSenderId: '227408311679',
    projectId: 'quiz-89939',
    authDomain: 'quiz-89939.firebaseapp.com',
    storageBucket: 'quiz-89939.firebasestorage.app',
    measurementId: 'G-E3N5DZBGKZ',
  );
}
